// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnzofKoWDgdycv456ay5QoLVvIxd_MOxE',
    appId: '1:888739413342:web:92211d1f63c3822bdf23cf',
    messagingSenderId: '888739413342',
    projectId: 'notice-6f051',
    authDomain: 'notice-6f051.firebaseapp.com',
    storageBucket: 'notice-6f051.appspot.com',
    measurementId: 'G-TTN0NZE765',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSFoeF_GcshO2WOXgv98L-BSkkeiHL52U',
    appId: '1:888739413342:android:1c1ada94dd7f9365df23cf',
    messagingSenderId: '888739413342',
    projectId: 'notice-6f051',
    storageBucket: 'notice-6f051.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdGdFYVfsVYdajK7aBeeczQEVEyeqlzdM',
    appId: '1:888739413342:ios:4c5738f295373c8adf23cf',
    messagingSenderId: '888739413342',
    projectId: 'notice-6f051',
    storageBucket: 'notice-6f051.appspot.com',
    iosClientId: '888739413342-ejlsenlaregln6ci3htkvh8opfb1l0nd.apps.googleusercontent.com',
    iosBundleId: 'com.example.notice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdGdFYVfsVYdajK7aBeeczQEVEyeqlzdM',
    appId: '1:888739413342:ios:4c5738f295373c8adf23cf',
    messagingSenderId: '888739413342',
    projectId: 'notice-6f051',
    storageBucket: 'notice-6f051.appspot.com',
    iosClientId: '888739413342-ejlsenlaregln6ci3htkvh8opfb1l0nd.apps.googleusercontent.com',
    iosBundleId: 'com.example.notice',
  );
}
